language: python
python: "2.7"
cache: pip
# use docker on Travis
sudo: false
install:
    - "pip install coveralls"
    - "pip install -r requirements.txt"
script: make test quality
branches:
    only:
      - master
after_success:
    - coveralls
    - bash ./scripts/build-stats-to-datadog.sh
